// Package harness holds helpers shared by the functional test suites under
// tests/functional. It knows how to find a Godot binary, create a throwaway
// Godot project, launch a headless editor against it, and speak MCP to either
// the editor (HTTP transport) or the CLI's MCP server (stdio transport).
package harness

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"time"

	"gitlab.com/snopek-games/godai/internal/isolation"
)

func RepoRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("cannot determine source file location")
	}
	// process.go lives four directories below the repo root.
	dir := filepath.Dir(file)
	for range 4 {
		dir = filepath.Dir(dir)
	}
	return dir
}

// ExePath is where to build a binary named name. Windows needs the extension:
// nothing will run the file without it.
func ExePath(dir, name string) string {
	if runtime.GOOS == "windows" {
		name += ".exe"
	}
	return filepath.Join(dir, name)
}

func FindGodot() (string, error) {
	if bin := os.Getenv("GODOT"); bin != "" {
		path, err := exec.LookPath(bin)
		if err != nil {
			return "", fmt.Errorf("GODOT is set but not usable: %w", err)
		}
		return path, nil
	}
	for _, name := range []string{"godot", "godot4"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("no Godot binary found (set the GODOT environment variable)")
}

// Below the Linux ephemeral range (32768+) so outbound connections can't steal
// a port from a slow-starting editor, and clear of the 12120+ window godai and godai-eval use.
const (
	MCPPortBase  = 23120
	MCPPortCount = 64
)

func MCPPortEnv() []string {
	return []string{
		fmt.Sprintf("GODAI_MCP_BASE_PORT=%d", MCPPortBase),
		fmt.Sprintf("GODAI_MCP_PORT_COUNT=%d", MCPPortCount),
	}
}

// IsolationDir returns the directory LaunchEditor redirects the editor's
// user dirs into: dot-prefixed under base so the Godot importer ignores it
// when base is the project directory.
func IsolationDir(base string) string {
	return filepath.Join(base, ".home")
}

// OpenTimeout returns GODAI_OPEN_TIMEOUT (the same variable godai itself
// reads) as a duration, or fallback when it's unset or invalid.
func OpenTimeout(fallback time.Duration) time.Duration {
	secs, err := strconv.ParseFloat(os.Getenv("GODAI_OPEN_TIMEOUT"), 64)
	if err != nil || secs <= 0 {
		return fallback
	}
	return time.Duration(secs * float64(time.Second))
}

func WaitForInstancePort(dir string, timeout time.Duration) (int, error) {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		entries, _ := os.ReadDir(dir)
		for _, entry := range entries {
			if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
				continue
			}
			b, err := os.ReadFile(filepath.Join(dir, entry.Name()))
			if err != nil {
				continue
			}
			var inst struct {
				Port int `json:"port"`
			}
			if json.Unmarshal(b, &inst) == nil && inst.Port > 0 {
				return inst.Port, nil
			}
		}
		time.Sleep(500 * time.Millisecond)
	}
	return 0, fmt.Errorf("no editor instance file with a port appeared in %s", dir)
}

type ProjectOptions struct {
	Name string
	// Leave false to let open_godot_project install the addon instead.
	InstallAddon bool
	// Needed when a client connects without knowing the secret (the editor HTTP
	// tests); the Go server reads the secret from the editor's instance file.
	SkipSecretCheck bool
}

func CreateTestProject(dir string, opts ProjectOptions) error {
	if opts.InstallAddon {
		addonSrc := filepath.Join(RepoRoot(), "addons", "godai")
		if err := os.CopyFS(filepath.Join(dir, "addons", "godai"), os.DirFS(addonSrc)); err != nil {
			return err
		}
	}

	projectGodot := "; Generated by the godai functional tests.\n" +
		"config_version=5\n\n" +
		"[application]\n\n" +
		"config/name=\"" + opts.Name + "\"\n" +
		"config/features=PackedStringArray(\"4.6\")\n"
	if opts.SkipSecretCheck {
		projectGodot += "\n[editor_overrides]\n\ngodai/mcp/skip_secret_check=true\n"
	}
	if opts.InstallAddon {
		projectGodot += "\n[autoload]\n\nGodai=\"*res://addons/godai/game/godai.gd\"\n"
		projectGodot += "\n[editor_plugins]\n\nenabled=PackedStringArray(\"res://addons/godai/plugin.cfg\")\n"
	}

	files := map[string]string{
		"project.godot": projectGodot,
		"fixtures/simple_node.gd": `extends Node


func describe() -> String:
	return "simple"
`,
		// An importable asset (imported as a texture), for the import tools.
		"icon.svg": `<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg"><rect width="128" height="128" fill="#478cbf"/></svg>`,
		"fixtures/custom_resource.gd": `class_name GodaiTestCustomResource
extends Resource

@export var title: String = ""
@export var amount: int = 0
`,
		"fixtures/scene_with_script.tscn": `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://fixtures/simple_node.gd" id="1_script"]

[node name="SceneWithScript" type="Node"]
script = ExtResource("1_script")

[node name="Child" type="Node2D" parent="."]

[node name="GrandChild" type="Node" parent="Child"]
`,
	}

	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}

	return nil
}

type EditorOptions struct {
	// "http" or "websocket"/"ws"; empty means the editor default (WebSocket).
	Transport string
	// Directory the editor's isolated user dirs go under (see IsolationDir).
	// Defaults to projectDir.
	IsolationBase string
	// Lets the restart_editor and close_editor tools run end-to-end without
	// actually shutting down the editor the harness manages.
	DisableShutdown bool
	// Leaves auto-approval off, so tools needing the user's approval are denied
	// instead. Only useful for testing that denial path: every other test wants
	// approval granted, since a headless editor has nobody to answer the dialog.
	NoAutoApproveTools bool
	Verbose            bool
	ExtraEnv           []string
}

func LaunchEditor(godotBin, projectDir string, opts EditorOptions) (*exec.Cmd, string, error) {
	// Use the explicit "--display-driver headless --audio-driver Dummy" form
	// rather than the "--headless" shortcut: they're equivalent, but Godot
	// forwards --display-driver/--audio-driver (and their values) to the
	// re-launched process when the editor restarts itself, whereas the
	// --headless shortcut is dropped. This keeps a restarted editor headless.
	cmd := exec.Command(godotBin, "--editor", "--display-driver", "headless", "--audio-driver", "Dummy", "--path", projectDir)

	env := os.Environ()
	if opts.Transport != "" {
		env = append(env, "GODAI_MCP_TRANSPORT="+opts.Transport)
	}
	env = append(env, MCPPortEnv()...)
	if !opts.NoAutoApproveTools {
		// Nobody is there to answer the approval dialog in a headless editor, so
		// without this every tool that needs approval would be denied.
		env = append(env, "GODAI_AUTO_APPROVE_TOOLS=1")
	}
	if opts.DisableShutdown {
		env = append(env, "GODAI_DISABLE_CLOSE=1")
	}

	// Point Godot's config/data/cache at temporary dirs so the tests get a
	// deterministic default and don't touch the user's real editor settings or
	// godai's real instances dir.
	base := opts.IsolationBase
	if base == "" {
		base = projectDir
	}
	isolationEnv, err := isolation.Env(IsolationDir(base))
	if err != nil {
		return nil, "", err
	}
	env = append(env, isolationEnv...)

	env = append(env, opts.ExtraEnv...)
	cmd.Env = env

	logPath := filepath.Join(projectDir, "editor.log")
	out, release, err := CaptureOutput(logPath, opts.Verbose)
	if err != nil {
		return nil, "", err
	}
	cmd.Stdout = out
	cmd.Stderr = out

	// Fix hang on the restart editor test.
	cmd.WaitDelay = 10 * time.Second

	err = cmd.Start()
	release()
	if err != nil {
		return nil, "", err
	}

	return cmd, logPath, nil
}

// CaptureOutput opens path for a child process to write to. The returned func
// must be called once the child has started: Windows won't remove a
// directory holding a file anything still has open.
func CaptureOutput(path string, verbose bool) (*os.File, func(), error) {
	file, err := os.Create(path)
	if err != nil {
		return nil, nil, err
	}
	if !verbose {
		return file, func() { file.Close() }, nil
	}

	reader, writer, err := os.Pipe()
	if err != nil {
		file.Close()
		return nil, nil, err
	}
	go func() {
		io.Copy(io.MultiWriter(file, os.Stderr), reader)
		reader.Close()
		file.Close()
	}()
	return writer, func() { writer.Close() }, nil
}

func StopEditor(cmd *exec.Cmd) {
	if cmd == nil || cmd.Process == nil {
		return
	}

	AskToStop(cmd.Process)

	done := make(chan struct{})
	go func() {
		cmd.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(15 * time.Second):
		cmd.Process.Kill()
		<-done
	}
}
