// Package harness holds helpers shared by the functional test suites under
// tests/functional. It knows how to find a Godot binary, create a throwaway
// Godot project, launch a headless editor against it, and speak MCP to either
// the editor (HTTP transport) or the CLI's MCP server (stdio transport).
package harness

import (
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"time"
)

func RepoRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("cannot determine source file location")
	}
	// process.go lives four directories below the repo root.
	dir := filepath.Dir(file)
	for range 4 {
		dir = filepath.Dir(dir)
	}
	return dir
}

func FindGodot() (string, error) {
	if bin := os.Getenv("GODOT"); bin != "" {
		path, err := exec.LookPath(bin)
		if err != nil {
			return "", fmt.Errorf("GODOT is set but not usable: %w", err)
		}
		return path, nil
	}
	for _, name := range []string{"godot", "godot4"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("no Godot binary found (set the GODOT environment variable)")
}

func FindFreePort() (int, error) {
	l, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port, nil
}

type ProjectOptions struct {
	Name string
	// Leave false to let open_godot_project install the addon instead.
	InstallAddon bool
	// Needed when a client connects without knowing the secret (the editor HTTP
	// tests); the Go server reads the secret from the editor's instance file.
	SkipSecretCheck bool
}

func CreateTestProject(dir string, opts ProjectOptions) error {
	if opts.InstallAddon {
		addonSrc := filepath.Join(RepoRoot(), "addons", "godai")
		if err := os.CopyFS(filepath.Join(dir, "addons", "godai"), os.DirFS(addonSrc)); err != nil {
			return err
		}
	}

	projectGodot := "; Generated by the godai functional tests.\n" +
		"config_version=5\n\n" +
		"[application]\n\n" +
		"config/name=\"" + opts.Name + "\"\n" +
		"config/features=PackedStringArray(\"4.6\")\n"
	if opts.SkipSecretCheck {
		projectGodot += "\n[editor_overrides]\n\ngodai/mcp/skip_secret_check=true\n"
	}
	if opts.InstallAddon {
		projectGodot += "\n[autoload]\n\nGodai=\"*res://addons/godai/game/godai.gd\"\n"
		projectGodot += "\n[editor_plugins]\n\nenabled=PackedStringArray(\"res://addons/godai/plugin.cfg\")\n"
	}

	files := map[string]string{
		"project.godot": projectGodot,
		"fixtures/simple_node.gd": `extends Node


func describe() -> String:
	return "simple"
`,
		// An importable asset (imported as a texture), for the import tools.
		"icon.svg": `<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg"><rect width="128" height="128" fill="#478cbf"/></svg>`,
		"fixtures/custom_resource.gd": `class_name GodaiTestCustomResource
extends Resource

@export var title: String = ""
@export var amount: int = 0
`,
		"fixtures/scene_with_script.tscn": `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://fixtures/simple_node.gd" id="1_script"]

[node name="SceneWithScript" type="Node"]
script = ExtResource("1_script")

[node name="Child" type="Node2D" parent="."]

[node name="GrandChild" type="Node" parent="Child"]
`,
	}

	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}

	return nil
}

type EditorOptions struct {
	Port int
	// "http" or "websocket"/"ws"; empty means the editor default (WebSocket).
	Transport string
	// Directory holding per-editor .xdg/<VAR> dirs. Defaults to projectDir.
	XDGBase string
	// Lets the restart_editor and close_editor tools run end-to-end without
	// actually shutting down the editor the harness manages.
	DisableShutdown bool
	// Leaves auto-approval off, so tools needing the user's approval are denied
	// instead. Only useful for testing that denial path: every other test wants
	// approval granted, since a headless editor has nobody to answer the dialog.
	NoAutoApproveTools bool
	Verbose            bool
	ExtraEnv           []string
}

func LaunchEditor(godotBin, projectDir string, opts EditorOptions) (*exec.Cmd, string, error) {
	// Use the explicit "--display-driver headless --audio-driver Dummy" form
	// rather than the "--headless" shortcut: they're equivalent, but Godot
	// forwards --display-driver/--audio-driver (and their values) to the
	// re-launched process when the editor restarts itself, whereas the
	// --headless shortcut is dropped. This keeps a restarted editor headless.
	cmd := exec.Command(godotBin, "--editor", "--display-driver", "headless", "--audio-driver", "Dummy", "--path", projectDir)

	env := os.Environ()
	if opts.Transport != "" {
		env = append(env, "GODAI_MCP_TRANSPORT="+opts.Transport)
	}
	env = append(env,
		fmt.Sprintf("GODAI_MCP_BASE_PORT=%d", opts.Port),
		"GODAI_MCP_PORT_COUNT=1",
	)
	if !opts.NoAutoApproveTools {
		// Nobody is there to answer the approval dialog in a headless editor, so
		// without this every tool that needs approval would be denied.
		env = append(env, "GODAI_AUTO_APPROVE_TOOLS=1")
	}
	if opts.DisableShutdown {
		env = append(env, "GODAI_DISABLE_CLOSE=1")
	}

	// Point Godot's config/data/cache at temporary XDG dirs so the tests get a
	// deterministic default and don't touch the user's real editor settings or
	// ~/.cache/godai/instances.
	xdgBase := opts.XDGBase
	if xdgBase == "" {
		xdgBase = projectDir
	}
	for _, v := range []string{"XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_CACHE_HOME"} {
		xdgDir := filepath.Join(xdgBase, ".xdg", v)
		if err := os.MkdirAll(xdgDir, 0o755); err != nil {
			return nil, "", err
		}
		env = append(env, fmt.Sprintf("%s=%s", v, xdgDir))
	}

	env = append(env, opts.ExtraEnv...)
	cmd.Env = env

	logPath := filepath.Join(projectDir, "editor.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		return nil, "", err
	}

	var out io.Writer = logFile
	if opts.Verbose {
		out = io.MultiWriter(logFile, os.Stderr)
	}
	cmd.Stdout = out
	cmd.Stderr = out

	// Fix hang on the restart editor test.
	cmd.WaitDelay = 10 * time.Second

	if err := cmd.Start(); err != nil {
		logFile.Close()
		return nil, "", err
	}

	return cmd, logPath, nil
}

func StopEditor(cmd *exec.Cmd) {
	if cmd == nil || cmd.Process == nil {
		return
	}

	cmd.Process.Signal(os.Interrupt)

	done := make(chan struct{})
	go func() {
		cmd.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(15 * time.Second):
		cmd.Process.Kill()
		<-done
	}
}
