// Package editor contains end-to-end tests that connect to a real Godot
// editor over the MCP HTTP transport and exercise the editor's MCP server,
// including the tools in addons/godai/tools/default/*_tools.gd.
//
// By default, a temporary Godot project is created (with the addon copied
// into it) and a headless editor is launched against it. Alternatively, set
// GODAI_TEST_PORT to connect to an already-running editor.
//
// Environment variables:
//   - GODOT: path to the Godot binary (otherwise "godot" or "godot4" from PATH)
//   - GODAI_TEST_PORT: connect to an editor already listening on this port,
//     instead of launching a headless one
//   - GODAI_TEST_VERBOSE: stream the editor log to stderr
//   - GODAI_TEST_KEEP: keep the temporary project directory after the run
package editor

import (
	"context"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strconv"
	"testing"
	"time"
)

var (
	client *Client

	// projectDir is the Godot project the editor is running. It is empty when
	// connecting to an external editor via GODAI_TEST_PORT, in which case
	// tests that need to inspect the project directory are skipped.
	projectDir string
)

const projectName = "Godai Functional Test"

func TestMain(m *testing.M) {
	flag.Parse()
	os.Exit(testMain(m))
}

func testMain(m *testing.M) int {
	if testing.Short() {
		fmt.Fprintln(os.Stderr, "SKIP: functional tests don't run in -short mode")
		return 0
	}

	ctx := context.Background()

	if portStr := os.Getenv("GODAI_TEST_PORT"); portStr != "" {
		client = NewClient("http://127.0.0.1:" + portStr)
		if err := waitForEditor(ctx, 10*time.Second); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL: cannot connect to editor on port %s: %v\n", portStr, err)
			return 1
		}
		return m.Run()
	}

	godotBin, err := findGodot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "SKIP: functional tests: %v\n", err)
		return 0
	}

	dir, err := os.MkdirTemp("", "godai-functional-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: %v\n", err)
		return 1
	}
	projectDir = dir

	if err := createTestProject(projectDir); err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: creating test project: %v\n", err)
		return 1
	}

	port, err := findFreePort()
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: %v\n", err)
		return 1
	}
	client = NewClient("http://127.0.0.1:" + strconv.Itoa(port))

	cmd, logPath, err := launchEditor(godotBin, projectDir, port)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: launching editor: %v\n", err)
		return 1
	}

	code := 1
	defer func() {
		stopEditor(cmd)
		if code != 0 {
			fmt.Fprintf(os.Stderr, "Test project kept at %s (editor log: %s)\n", projectDir, logPath)
		} else if os.Getenv("GODAI_TEST_KEEP") != "" {
			fmt.Fprintf(os.Stderr, "Test project kept at %s\n", projectDir)
		} else {
			os.RemoveAll(projectDir)
		}
	}()

	// The first launch has to import the whole project, which can be slow.
	if err := waitForEditor(ctx, 180*time.Second); err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: editor never became ready: %v\n", err)
		return 1
	}

	code = m.Run()
	return code
}

// repoRoot returns the absolute path to the repository root, based on the
// location of this source file (tests/functional/editor/main_test.go).
func repoRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		panic("cannot determine source file location")
	}
	return filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(file))))
}

func findGodot() (string, error) {
	if bin := os.Getenv("GODOT"); bin != "" {
		path, err := exec.LookPath(bin)
		if err != nil {
			return "", fmt.Errorf("GODOT is set but not usable: %w", err)
		}
		return path, nil
	}
	for _, name := range []string{"godot", "godot4"} {
		if path, err := exec.LookPath(name); err == nil {
			return path, nil
		}
	}
	return "", fmt.Errorf("no Godot binary found (set the GODOT environment variable)")
}

func findFreePort() (int, error) {
	l, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		return 0, err
	}
	defer l.Close()
	return l.Addr().(*net.TCPAddr).Port, nil
}

// createTestProject writes a minimal Godot project with the godai addon
// enabled, plus some fixture files used by the tests.
func createTestProject(dir string) error {
	addonSrc := filepath.Join(repoRoot(), "addons", "godai")
	if err := os.CopyFS(filepath.Join(dir, "addons", "godai"), os.DirFS(addonSrc)); err != nil {
		return err
	}

	files := map[string]string{
		"project.godot": `; Generated by the godai functional tests.
config_version=5

[application]

config/name="` + projectName + `"
config/features=PackedStringArray("4.6")

[editor_plugins]

enabled=PackedStringArray("res://addons/godai/plugin.cfg")
`,
		"fixtures/simple_node.gd": `extends Node


func describe() -> String:
	return "simple"
`,
		// An importable asset (imported as a texture), for the import tools.
		"icon.svg": `<svg width="128" height="128" xmlns="http://www.w3.org/2000/svg"><rect width="128" height="128" fill="#478cbf"/></svg>`,
		"fixtures/custom_resource.gd": `class_name GodaiTestCustomResource
extends Resource

@export var title: String = ""
@export var amount: int = 0
`,
		"fixtures/scene_with_script.tscn": `[gd_scene load_steps=2 format=3]

[ext_resource type="Script" path="res://fixtures/simple_node.gd" id="1_script"]

[node name="SceneWithScript" type="Node"]
script = ExtResource("1_script")

[node name="Child" type="Node2D" parent="."]

[node name="GrandChild" type="Node" parent="Child"]
`,
	}

	for name, content := range files {
		path := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return err
		}
	}

	return nil
}

func launchEditor(godotBin, dir string, port int) (*exec.Cmd, string, error) {
	cmd := exec.Command(godotBin, "--editor", "--headless", "--path", dir)
	cmd.Env = append(os.Environ(),
		"GODAI_MCP_TRANSPORT=http",
		fmt.Sprintf("GODAI_MCP_BASE_PORT=%d", port),
		"GODAI_MCP_PORT_COUNT=1",
		// Let the restart_editor tool run end-to-end without actually
		// restarting (which would kill the editor this harness manages).
		"GODAI_DISABLE_RESTART=1",
	)

	// Point Godot's editor config/data/cache at temporary directories (it
	// honours the XDG base-dir variables on Linux). This keeps the user's real
	// editor settings out of the tests, and gives editor-settings tests a
	// deterministic, default starting point.
	for _, v := range []string{"XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_CACHE_HOME"} {
		xdgDir := filepath.Join(dir, ".xdg", v)
		if err := os.MkdirAll(xdgDir, 0o755); err != nil {
			return nil, "", err
		}
		cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", v, xdgDir))
	}

	logPath := filepath.Join(dir, "editor.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		return nil, "", err
	}

	var out io.Writer = logFile
	if os.Getenv("GODAI_TEST_VERBOSE") != "" {
		out = io.MultiWriter(logFile, os.Stderr)
	}
	cmd.Stdout = out
	cmd.Stderr = out

	if err := cmd.Start(); err != nil {
		logFile.Close()
		return nil, "", err
	}

	return cmd, logPath, nil
}

func stopEditor(cmd *exec.Cmd) {
	if cmd.Process == nil {
		return
	}

	cmd.Process.Signal(os.Interrupt)

	done := make(chan struct{})
	go func() {
		cmd.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(15 * time.Second):
		cmd.Process.Kill()
		<-done
	}
}

// waitForEditor polls the MCP endpoint until an initialize request succeeds.
func waitForEditor(ctx context.Context, timeout time.Duration) error {
	deadline := time.Now().Add(timeout)

	var lastErr error
	for time.Now().Before(deadline) {
		reqCtx, cancel := context.WithTimeout(ctx, 2*time.Second)
		_, lastErr = client.Initialize(reqCtx)
		cancel()
		if lastErr == nil {
			return nil
		}
		time.Sleep(500 * time.Millisecond)
	}

	return fmt.Errorf("timed out after %s: %w", timeout, lastErr)
}
